logging:
    level:
        com:
            azurealstn:
                codespringweb:
                    mapper: debug
        root: info

mybatis:
    configuration:
        call-setters-on-nulls: true
        jdbc-type-for-null: null
        map-underscore-to-camel-case: true
    mapper-locations: classpath:/mapper/**/*SqlMap.xml
    type-aliases-package: kr.co.seoulit.account

server:
    error:
        include-exception: true
    port: 9103

spring:
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:oracle:thin:@//106.242.162.220:1521/xe?oracle.jdbc.timezoneAsRegion=false
        username: NexaAcc78
        password: NexaAcc78

    main:
        allow-bean-definition-overriding: true

    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp

    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB

    kafka:
        bootstrap-servers: here
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
            group-id: kafka-react-logi-acc
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            properties:
                key.deserializer.encoding: UTF8
                value.deserializer.encoding: UTF8

tomcat:
    ajp:
        enabled: true
        port: 8009
        protocol: AJP/1.3
        remoteauthentication: false

FRONTEND_SERVICE_URL: http://$accFrontendUrl
